<a href="https://colab.research.google.com/github/uyenndt1210/thuchanh-deeplearning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

## Tạo array 1-chiều

In [ ]:
import numpy as np
#cách 1
my_list = [1, 9, 15, 39]
print('Danh sách Python:', my_list)
my_numpy_array = np.array(my_list)
print('Mảng Numpy:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)

Danh sách Python: [1, 9, 15, 39]
Mảng Numpy: [ 1  9 15 39]
[ 1  9 15 39]


## Array 2 chiều

In [ ]:
c = np.array([(1, 2, 3),(4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Array 3-chiều

In [ ]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]],[[7., 8., 9.], [10, 11, 12]]])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


## Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Ma trận không: \n', e)
print('Một ma trận\n', f)

Ma trận không: 
 [[0. 0.]
 [0. 0.]]
Một ma trận
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape thay đổi kích thước ma trận

In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape (3,2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]] ])
print(g)
print(g.shape)

h = g.reshape(3,4)
print('reshape (3, 4)\n',h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


## Flatten là chuyển array nhiều chiều về 1 chiều

In [2]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack

In [3]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số nguyên ngẫu nhiên

In [4]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [77 75  7 48  1]
Random 2-D array
 [[67 37 42 51]
 [84 78 19 68]
 [99 57 21 67]]
Random 3-D array
 [[[67 30 49]
  [70 65 17]
  [40 95 71]
  [ 2 21 26]]

 [[ 8 61 65]
  [15 17 78]
  [38 67 22]
  [27 39 83]]

 [[16 81 95]
  [82 69 53]
  [59 11  8]
  [30 59 50]]]


## Sinh mảng số thực trong khoảng [0, 1]

In [5]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.88490378 0.04911506 0.0758542  0.87830446 0.39522723]
Random 2-D array
 [[0.8637944  0.79690973 0.30947061 0.33516124]
 [0.55743299 0.61949397 0.07824676 0.82393417]
 [0.47577618 0.43490056 0.070093   0.79672136]]
Random 3-D array
 [[[0.87793222 0.11275866 0.52511306]
  [0.80304244 0.58562538 0.91375115]
  [0.91540312 0.76774238 0.02545174]
  [0.30093517 0.9571383  0.57276986]]

 [[0.28052405 0.81052657 0.52948309]
  [0.95743132 0.30695297 0.68575825]
  [0.92741827 0.24900138 0.55774862]
  [0.92423972 0.86646321 0.86907022]]

 [[0.8071621  0.361929   0.60646498]
  [0.679777   0.95653171 0.67492454]
  [0.59903825 0.73156994 0.39461003]
  [0.94630732 0.8888215  0.31855568]]]


## Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [6]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.27385588 4.85325732 5.43661804 5.26457842 5.40412404 6.22703127
 6.63982556 5.55088735 4.89670049 4.47068751]


## Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [7]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

4
[[18  2 12 14  4]
 [14  4  8  8 10]
 [16 20 14 10  8]]


## Thay đổi giá trị của ma trận

In [8]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Dùng hàm arange

In [9]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


## Dùng hàm linspace

In [10]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Index và slice

In [11]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


# PANDAS

## TÌM HIỂU ĐỐI TƯỢNG SERIES

In [13]:
import pandas as pd

a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


## TẠO ĐỐI TƯỢNG DATAFRAME

In [14]:
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


## Tạo DataFrame mảng 2-chiều có tên cột

In [18]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

r = np.random.random((20, 4))

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.573843  0.103087  0.658254  0.126600
1  0.909701  0.330428  0.680212  0.192274
2  0.170271  0.021743  0.394376  0.049138
3  0.461556  0.815064  0.544547  0.360156
4  0.891371  0.442161  0.217374  0.601002


## Slice DataFrame

In [19]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

print('Chọn cột so1\n', df['so1'])
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  0.229437  0.291221 -1.009090 -0.601150
1 -1.018055 -0.158038 -0.226878  1.143321
2 -1.054459 -0.262777 -1.658493  0.088660
3  1.183768 -0.508004  0.685826  1.594521
4 -1.170239 -0.289040 -0.633489  0.261492
Chọn cột so1
 0     0.229437
1    -1.018055
2    -1.054459
3     1.183768
4    -1.170239
5     0.447909
6     1.136195
7     0.837500
8     0.789036
9    -2.049685
10   -0.427811
11    0.109029
12    0.955727
13    1.346849
14    0.091258
15    0.414121
16   -0.789443
17   -0.235666
18    0.062746
19   -0.896100
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  0.229437  0.291221 -1.009090 -0.601150
1 -1.018055 -0.158038 -0.226878  1.143321
2 -1.054459 -0.262777 -1.658493  0.088660
Chọn nhiều cột
          so1       so3
0   0.229437 -1.009090
1  -1.018055 -0.226878
2  -1.054459 -1.658493
3   1.183768  0.685826
4  -1.170239 -0.633489
5   0.447909  0.002006
6   1.136195  0.708001
7   0.837500 -0.584297


## Nối nhiều DataFrame

In [20]:
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]}, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concat two DataFrame\n', df_concat)

print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concat two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


## Bài 10

In [22]:
import numpy as np

# Tạo ma trận 10x10 toàn 0
matrix = np.zeros((10, 10), dtype=int)

# Đặt giá trị biên = 1
matrix[0, :] = 1      # Hàng đầu tiên
matrix[-1, :] = 1     # Hàng cuối cùng
matrix[:, 0] = 1      # Cột đầu tiên
matrix[:, -1] = 1     # Cột cuối cùng

print("Ma trận 10x10:\n")
print(matrix)

Ma trận 10x10:

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Bài 22

In [23]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print("DataFrame đầy đủ:\n")
print(df)

DataFrame đầy đủ:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
