<a href="https://colab.research.google.com/github/uyenndt1210/thuchanh-deeplearning/blob/main/Buoi2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vấn đề 1

In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

## Tạo file csv

In [5]:
data = """
ID,Name,Gender,Age,Height,Weight,ExerciseHours
1,Nguyen Van A ,Male,20,170cm,65kg,2
2,TRAN THI B,Female,19,1.58m,50kgs,3
3,le van c,male,21,165 cm,154lbs,
4,Pham Thi D,FEMALE,,160cm,48kg,4
5,Nguyen Van A ,Male,20,170cm,65kg,2
6, Hoang Van E,Male,22,,70kg,5
7,Do Thi F,Female,20,155cm,,three
"""

with open("student_health.csv", "w") as f:
    f.write(data)

print("Đã tạo file student_health.csv")

Đã tạo file student_health.csv


## Đọc dữ liệu

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_health.csv")

print(df)

   ID           Name  Gender   Age  Height  Weight ExerciseHours
0   1  Nguyen Van A     Male  20.0   170cm    65kg             2
1   2     TRAN THI B  Female  19.0   1.58m   50kgs             3
2   3       le van c    male  21.0  165 cm  154lbs           NaN
3   4     Pham Thi D  FEMALE   NaN   160cm    48kg             4
4   5  Nguyen Van A     Male  20.0   170cm    65kg             2
5   6    Hoang Van E    Male  22.0     NaN    70kg             5
6   7       Do Thi F  Female  20.0   155cm     NaN         three


## Data cleaning

In [59]:
# =========================
# BƯỚC 4: LÀM SẠCH DỮ LIỆU TEXT
# =========================
df["Gender"] = df["Gender"].astype(str).str.lower().str.strip()
# =========================
# BƯỚC 5: CHUẨN HÓA HEIGHT
# =========================

df["Height"] = (
    df["Height"]
    .astype(str)
    .str.replace(r"[a-zA-Z\s]", "", regex=True)
)

df["Height"] = pd.to_numeric(df["Height"], errors="coerce")

df["Height"] = np.where(
    df["Height"] < 3,
    df["Height"] * 100,
    df["Height"]
)

print(df[["Name", "Height"]])


# =========================
# BƯỚC 6: CHUẨN HÓA WEIGHT
# =========================

is_lbs = df["Weight"].astype(str).str.contains("lbs", na=False)

df["Weight"] = (
    df["Weight"]
    .astype(str)
    .str.replace(r"[a-zA-Z\s]", "", regex=True)
)

df["Weight"] = pd.to_numeric(df["Weight"], errors="coerce")

df["Weight"] = np.where(
    is_lbs,
    df["Weight"] * 0.453592,
    df["Weight"]
)

print(df[["Name", "Weight"]])


# =========================
# BƯỚC 7: CHUẨN HÓA ExerciseHours
# =========================
df["ExerciseHours"] = pd.to_numeric(
    df["ExerciseHours"],
    errors="coerce"
)

print(df[["Name", "ExerciseHours"]])

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Height"] = df["Height"].fillna(df["Height"].mean())

df["Weight"] = df["Weight"].fillna(df["Weight"].mean())

df["ExerciseHours"] = df["ExerciseHours"].fillna(
    df["ExerciseHours"].mean()
)

# =========================
# BƯỚC 8: XÓA DỮ LIỆU TRÙNG
# =========================

df = df.drop_duplicates()

print(df)

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

print(df[["Gender"]])

           Name  Height
0  Nguyen Van A   170.0
1    Tran Thi B   158.0
2      Le Van C   165.0
3    Pham Thi D   160.0
4  Nguyen Van A   170.0
5   Hoang Van E   163.0
6      Do Thi F   155.0
           Name  Weight
0  Nguyen Van A    65.0
1    Tran Thi B    50.0
2      Le Van C    69.9
3    Pham Thi D    48.0
4  Nguyen Van A    65.0
5   Hoang Van E    70.0
6      Do Thi F    61.3
           Name  ExerciseHours
0  Nguyen Van A            2.0
1    Tran Thi B            3.0
2      Le Van C            3.2
3    Pham Thi D            4.0
4  Nguyen Van A            2.0
5   Hoang Van E            5.0
6      Do Thi F            3.0
   ID          Name Gender        Age  Height  Weight  ExerciseHours
0   1  Nguyen Van A      1  20.000000   170.0    65.0            2.0
1   2    Tran Thi B      0  19.000000   158.0    50.0            3.0
2   3      Le Van C      1  21.000000   165.0    69.9            3.2
3   4    Pham Thi D      0  20.333333   160.0    48.0            4.0
4   5  Nguyen Van A    

In [44]:
X = df[["Gender", "Age", "Height", "Weight"]]

y = df["ExerciseHours"]

In [49]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [52]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

print(X)

[[ 8.66025404e-01 -3.81881308e-01  1.30958009e+00  4.44348361e-01]
 [-1.15470054e+00 -1.52752523e+00 -9.35414347e-01 -1.36404613e+00]
 [ 8.66025404e-01  7.63762616e-01  3.74165739e-01  1.03509056e+00]
 [-1.15470054e+00 -1.19745483e-15 -5.61248608e-01 -1.60516540e+00]
 [ 8.66025404e-01 -3.81881308e-01  1.30958009e+00  4.44348361e-01]
 [ 8.66025404e-01  1.90940654e+00  6.34413157e-17  1.04714652e+00]
 [-1.15470054e+00 -3.81881308e-01 -1.49666295e+00 -1.72228047e-03]]


In [36]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    verbose=1
)


=== X_train_scaled ===
[[-1.09108945 -1.52656362 -0.1113623 ]
 [ 0.21821789  1.12832963  0.84635351]
 [ 1.52752523  0.59735098  0.85748974]
 [-0.65465367 -0.19911699 -1.59248094]]

=== X_test_scaled ===
[[-1.09108945  2.45577625  0.30067822]
 [-2.40039679 -0.73009564 -1.36975633]]


In [55]:
import numpy as np

# ==========================================
# 1. KHỞI TẠO THAM SỐ (Weights và Bias)
# ==========================================
# X_train của bạn có 3 cột (Age, Height, Weight)
num_features = X_train.shape[1]

# Khởi tạo ngẫu nhiên hoặc bằng 0
W = np.zeros(num_features)
b = 0.0

# Thiết lập siêu tham số (Hyperparameters)
learning_rate = 0.01  # Tốc độ học
epochs = 100          # Số lượt học
m = len(X_train)      # Số lượng mẫu dữ liệu (dòng) trong tập Train

# Chuyển đổi y_train, y_test về dạng mảng NumPy để tính toán không bị lỗi
y_train_arr = np.array(y_train)
y_test_arr = np.array(y_test)

# ==========================================
# 2. VÒNG LẶP HUẤN LUYỆN (Gradient Descent)
# ==========================================
for epoch in range(epochs):
    # Bước 2.1: Dự đoán đầu ra (Forward Pass)
    y_pred_train = np.dot(X_train, W) + b

    # Bước 2.2: Tính toán Đạo hàm (Gradients) theo công thức toán
    dW = (2/m) * np.dot(X_train.T, (y_pred_train - y_train_arr))
    db = (2/m) * np.sum(y_pred_train - y_train_arr)

    # Bước 2.3: Cập nhật lại Weights và Bias (Hạ dốc)
    W = W - learning_rate * dW
    b = b - learning_rate * db

    # (Tùy chọn) In ra sai số sau mỗi 20 lượt để theo dõi
    if (epoch + 1) % 20 == 0:
        train_loss = np.mean((y_pred_train - y_train_arr) ** 2)
        print(f"Epoch {epoch+1}/{epochs} - Train Loss (MSE): {train_loss:.4f}")

print("\n--- Huấn luyện hoàn tất! ---\n")

# ==========================================
# 3. ĐÁNH GIÁ MÔ HÌNH TRÊN TẬP TEST (Evaluate)
# ==========================================
# Cho mô hình chạy trên tập X_test bằng bộ W và b đã tối ưu ở trên
y_pred_test = np.dot(X_test, W) + b

# Tự tính toán Loss (MSE) và MAE theo đúng công thức định nghĩa
loss = np.mean((y_pred_test - y_test_arr) ** 2)      # Mean Squared Error
mae = np.mean(np.abs(y_pred_test - y_test_arr))     # Mean Absolute Error

print("Loss (MSE) trên tập Test:", loss)
print("MAE trên tập Test:", mae)

Epoch 20/100 - Train Loss (MSE): 4.9633
Epoch 40/100 - Train Loss (MSE): 1.9843
Epoch 60/100 - Train Loss (MSE): 0.8636
Epoch 80/100 - Train Loss (MSE): 0.4135
Epoch 100/100 - Train Loss (MSE): 0.2190

--- Huấn luyện hoàn tất! ---

Loss (MSE) trên tập Test: 1.293049218258815
MAE trên tập Test: 1.0246453470961154


In [57]:
# CHUẨN: Dùng công thức toán y = X.W + b để đưa ra dự đoán (predictions)
predictions = np.dot(X_test, W) + b

# In kết quả dự đoán ra màn hình
print("Số giờ tập thể dục dự đoán cho tập Test:")
print(predictions)

Số giờ tập thể dục dự đoán cho tập Test:
[1.46845822 1.48225108]
