<a href="https://colab.research.google.com/github/uyenndt1210/thuchanh-deeplearning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

## Tạo array 1-chiều

In [ ]:
import numpy as np
#cách 1
my_list = [1, 9, 15, 39]
print('Danh sách Python:', my_list)
my_numpy_array = np.array(my_list)
print('Mảng Numpy:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)

Danh sách Python: [1, 9, 15, 39]
Mảng Numpy: [ 1  9 15 39]
[ 1  9 15 39]


## Array 2 chiều

In [ ]:
c = np.array([(1, 2, 3),(4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Array 3-chiều

In [ ]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]],[[7., 8., 9.], [10, 11, 12]]])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


## Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Ma trận không: \n', e)
print('Một ma trận\n', f)

Ma trận không: 
 [[0. 0.]
 [0. 0.]]
Một ma trận
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape thay đổi kích thước ma trận

In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape (3,2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]] ])
print(g)
print(g.shape)

h = g.reshape(3,4)
print('reshape (3, 4)\n',h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


## Flatten là chuyển array nhiều chiều về 1 chiều

In [2]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack

In [3]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số nguyên ngẫu nhiên

In [4]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [77 75  7 48  1]
Random 2-D array
 [[67 37 42 51]
 [84 78 19 68]
 [99 57 21 67]]
Random 3-D array
 [[[67 30 49]
  [70 65 17]
  [40 95 71]
  [ 2 21 26]]

 [[ 8 61 65]
  [15 17 78]
  [38 67 22]
  [27 39 83]]

 [[16 81 95]
  [82 69 53]
  [59 11  8]
  [30 59 50]]]


## Sinh mảng số thực trong khoảng [0, 1]

In [5]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.88490378 0.04911506 0.0758542  0.87830446 0.39522723]
Random 2-D array
 [[0.8637944  0.79690973 0.30947061 0.33516124]
 [0.55743299 0.61949397 0.07824676 0.82393417]
 [0.47577618 0.43490056 0.070093   0.79672136]]
Random 3-D array
 [[[0.87793222 0.11275866 0.52511306]
  [0.80304244 0.58562538 0.91375115]
  [0.91540312 0.76774238 0.02545174]
  [0.30093517 0.9571383  0.57276986]]

 [[0.28052405 0.81052657 0.52948309]
  [0.95743132 0.30695297 0.68575825]
  [0.92741827 0.24900138 0.55774862]
  [0.92423972 0.86646321 0.86907022]]

 [[0.8071621  0.361929   0.60646498]
  [0.679777   0.95653171 0.67492454]
  [0.59903825 0.73156994 0.39461003]
  [0.94630732 0.8888215  0.31855568]]]


## Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [6]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.27385588 4.85325732 5.43661804 5.26457842 5.40412404 6.22703127
 6.63982556 5.55088735 4.89670049 4.47068751]


## Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [7]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

4
[[18  2 12 14  4]
 [14  4  8  8 10]
 [16 20 14 10  8]]


## Thay đổi giá trị của ma trận

In [8]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Dùng hàm arange

In [9]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


## Dùng hàm linspace

In [10]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Index và slice

In [11]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


# PANDAS

## TÌM HIỂU ĐỐI TƯỢNG SERIES

In [13]:
import pandas as pd

a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


## TẠO ĐỐI TƯỢNG DATAFRAME

In [14]:
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


## Tạo DataFrame mảng 2-chiều có tên cột

In [18]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

r = np.random.random((20, 4))

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.573843  0.103087  0.658254  0.126600
1  0.909701  0.330428  0.680212  0.192274
2  0.170271  0.021743  0.394376  0.049138
3  0.461556  0.815064  0.544547  0.360156
4  0.891371  0.442161  0.217374  0.601002


## Slice DataFrame

In [19]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

print('Chọn cột so1\n', df['so1'])
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  0.229437  0.291221 -1.009090 -0.601150
1 -1.018055 -0.158038 -0.226878  1.143321
2 -1.054459 -0.262777 -1.658493  0.088660
3  1.183768 -0.508004  0.685826  1.594521
4 -1.170239 -0.289040 -0.633489  0.261492
Chọn cột so1
 0     0.229437
1    -1.018055
2    -1.054459
3     1.183768
4    -1.170239
5     0.447909
6     1.136195
7     0.837500
8     0.789036
9    -2.049685
10   -0.427811
11    0.109029
12    0.955727
13    1.346849
14    0.091258
15    0.414121
16   -0.789443
17   -0.235666
18    0.062746
19   -0.896100
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  0.229437  0.291221 -1.009090 -0.601150
1 -1.018055 -0.158038 -0.226878  1.143321
2 -1.054459 -0.262777 -1.658493  0.088660
Chọn nhiều cột
          so1       so3
0   0.229437 -1.009090
1  -1.018055 -0.226878
2  -1.054459 -1.658493
3   1.183768  0.685826
4  -1.170239 -0.633489
5   0.447909  0.002006
6   1.136195  0.708001
7   0.837500 -0.584297


## Nối nhiều DataFrame

In [20]:
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]}, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concat two DataFrame\n', df_concat)

print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concat two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


## Bài 10

In [22]:
import numpy as np

# Tạo ma trận 10x10 toàn 0
matrix = np.zeros((10, 10), dtype=int)

# Đặt giá trị biên = 1
matrix[0, :] = 1      # Hàng đầu tiên
matrix[-1, :] = 1     # Hàng cuối cùng
matrix[:, 0] = 1      # Cột đầu tiên
matrix[:, -1] = 1     # Cột cuối cùng

print("Ma trận 10x10:\n")
print(matrix)

Ma trận 10x10:

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Bài 22

In [23]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print("DataFrame đầy đủ:\n")
print(df)

DataFrame đầy đủ:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# TENSORFLOW

## Tensor 0-chiều

In [24]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


## Tensor 1-chiều

In [25]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


## Tensor 2-chiều

In [26]:
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


## Tensor n-chiều

In [27]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## Thuộc tính của tensor

In [28]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],
])

print('rank_3_tensor')
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

rank_3_tensor
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


## Tạo tensor tự động gắn giá trị 0 ban đầu

In [29]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


## Tạo tensor tự động gắn giá trị 1 ban đầu

In [30]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3,3])
print(t_2_one)

t_3_one = tf.ones([3,3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


## Tạo tensor tự động với giá trị bất kỳ

In [31]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


## Tạo tensor 1-chiều với hàm linspace

In [32]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


## Tạo tensor 1-chiều với hàm range

In [33]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


## Tạo tensor với giá trị ngẫu nhiên

In [34]:
# random.normal
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3,3])
print(range_tensor)

# truncated_normal
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

# random.uniform
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

# shuffle
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([-0.40001714 -0.8227217   0.41149506  0.48633385  0.27356005], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.9515469  -0.9901237  -0.10366467]
 [ 0.51961535  0.9518365  -1.3112547 ]
 [ 0.01666644 -0.09707897 -0.28459734]], shape=(3, 3), dtype=float32)
tf.Tensor([ 1.8299904   0.9183994   0.15558055  0.5883224  -0.8244179 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.23608255 -0.90311646]
 [-0.8656365  -0.2618916 ]
 [ 0.40613878 -0.64334965]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[-1.2037095   0.8612613 ]
  [-1.1967915   1.6469742 ]]

 [[-0.53659266  0.16604142]
  [ 0.5910706   0.3390798 ]]

 [[ 0.45255044  1.0036128 ]
  [-0.4818527  -0.78010684]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor([15.80614  12.79627  16.369322 14.739733 11.065376], shape=(5,), dtype=float32)
tf.Tensor(
[[12.889762 16.621237]
 [15.929907 17.427149]
 [11.685894 12.169522]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[15.026392  17.954386  12.232447  16.625141  13.142085 ]
  [10.9923935 10.875306  17.2

## Chuyển đổi kiểu dữ liệu

In [35]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


## Các phép toán trong tensorflow

In [36]:
# Căn bậc 2
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

# Cộng
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

# Nhân
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

# Các phép toán khác
a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(l)

tf.Tensor(1.4142135, shape=(), dtype=float32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


## Các phép toán làm tròn và so sánh

In [37]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


## Các phép toán trên vector và ma trận

In [38]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3], [4, 5, 6]])
t4 = tf.constant([[7, 8], [9, 10], [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


## Biến trong tensorflow

In [39]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())


diem.assign([8, 10])
print(diem)

diem.assign_add([1, 1])
print(diem)

diem.assign_sub([5, 5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


## Biến một hàm Python thuần túy sang graph

In [ ]:
# Define a Python function.
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Use tf.function to make it a TensorFlow Function
@tf.function
def a_function_that_uses_a_graph(x, y, b):
    return a_regular_function(x, y, b)

# Example usage
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

## Modules, Layers và Models

In [40]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")
rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables:', simple_module.trainable_variables)
print('All variables:', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


In [41]:
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

my_model = SequentialModule(name="the_model")
print(my_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


## Lưu checkpoint

In [42]:
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)
print(chkp_path)

my_checkpoint


## Phục hồi checkpoint

In [43]:
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


## Bài 10

In [44]:
import tensorflow as tf

x = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.float32)
y = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.float32)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())


result = tf.where(x < y, x + y, x - y)

print("\nKết quả (x + y nếu x < y, x - y nếu x > y):")
print(result.numpy())

Tensor x: [4.2291155 4.8266706 7.2129498 8.838687  9.660032 ]
Tensor y: [1.3031197 1.77917   9.869345  3.9976478 9.59806  ]

Kết quả (x + y nếu x < y, x - y nếu x > y):
[ 2.9259958   3.0475006  17.082294    4.841039    0.06197262]


## Bài 12

In [45]:
import tensorflow as tf


def create_tensors():
    x = tf.random.uniform([3, 2, 2], minval=1, maxval=10, dtype=tf.float32)
    y = tf.random.uniform([3, 2, 2], minval=1, maxval=10, dtype=tf.float32)
    return x, y


@tf.function
def tensor_calculations(x, y):
    add = tf.add(x, y)          # hoặc x + y
    sub = tf.subtract(x, y)     # hoặc x - y
    mul = tf.multiply(x, y)     # hoặc x * y
    div = tf.divide(x, y)       # chia an toàn
    return add, sub, mul, div


x, y = create_tensors()

print("Tensor x shape:", x.shape)
print("Tensor y shape:", y.shape)
print("\nTensor x:\n", x.numpy())
print("Tensor y:\n", y.numpy())

add, sub, mul, div = tensor_calculations(x, y)

print("\n=== KẾT QUẢ SAU KHI CHẠY TRONG GRAPH ===")
print("Cộng   :", add.numpy())
print("Trừ    :", sub.numpy())
print("Nhân   :", mul.numpy())
print("Chia   :", div.numpy())

Tensor x shape: (3, 2, 2)
Tensor y shape: (3, 2, 2)

Tensor x:
 [[[9.3242    9.313093 ]
  [3.5800276 5.688702 ]]

 [[1.8394027 3.1215415]
  [3.018979  7.767446 ]]

 [[5.202203  8.767385 ]
  [2.7597747 9.050009 ]]]
Tensor y:
 [[[2.4482179 7.619661 ]
  [9.430069  8.587251 ]]

 [[4.2194214 7.5638866]
  [1.4524221 7.0390368]]

 [[1.9060298 2.9535956]
  [1.360079  6.1809816]]]

=== KẾT QUẢ SAU KHI CHẠY TRONG GRAPH ===
Cộng   : [[[11.772417  16.932755 ]
  [13.010097  14.275953 ]]

 [[ 6.058824  10.685429 ]
  [ 4.471401  14.806482 ]]

 [[ 7.1082325 11.72098  ]
  [ 4.119854  15.23099  ]]]
Trừ    : [[[ 6.875982   1.6934323]
  [-5.8500414 -2.8985486]]

 [[-2.3800187 -4.442345 ]
  [ 1.5665569  0.7284093]]

 [[ 3.296173   5.813789 ]
  [ 1.3996956  2.8690271]]]
Nhân   : [[[22.827673  70.96261  ]
  [33.759907  48.85031  ]]

 [[ 7.761215  23.610987 ]
  [ 4.384832  54.67534  ]]

 [[ 9.915554  25.89531  ]
  [ 3.7535117 55.93794  ]]]
Chia   : [[[3.808566   1.2222451 ]
  [0.3796396  0.6624591 ]]

 [[0.43