<a href="https://colab.research.google.com/github/uyenndt1210/thuchanh-deeplearning/blob/main/DeepLearning_Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Tạo array 1-chiều
import numpy as np
#cách 1
my_list = [1, 9, 15, 39]
print('Danh sách Python:', my_list)
my_numpy_array = np.array(my_list)
print('Mảng Numpy:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)

Danh sách Python: [1, 9, 15, 39]
Mảng Numpy: [ 1  9 15 39]
[ 1  9 15 39]


In [4]:
#Array 2 chiều
c = np.array([(1, 2, 3),(4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [5]:
#Array 3-chiều

d = np.array([[[1., 2., 3.], [4., 5., 6.]],[[7., 8., 9.], [10, 11, 12]]])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [6]:
#Tạo Array với giá trị ban đầu là 0 hoặc 1

e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Ma trận không: \n', e)
print('Một ma trận\n', f)

Ma trận không: 
 [[0. 0.]
 [0. 0.]]
Một ma trận
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Reshape to change the size of the matrix

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape (3,2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]] ])
print(g)
print(g.shape)

h = g.reshape(3,4)
print('reshape (3, 4)\n',h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
